name: 构建SM8475-11r内核

on:
  workflow_call:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Configure Git
      run: |
         git config --global user.name "zhanghao"
         git config --global user.email "114514@qq.com"
    
    - name: 安装repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo
    
    - name: 安装编译环境
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install curl git python3 -y

    - name: 拉取oneplus 11r内核清单
      run: |
        mkdir kernel && cd kernel
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth=1
        repo sync -j$(nproc --all)
        #sed -i 's/export REPACK_IMG=true/export REPACK_IMG=false/Ig' kernel_platform/oplus/build/oplus_setup.sh
        #sed -i 's/ -dirty$//' kernel_platform/common/scripts/setlocalversion
        #sed -i '1i CONFIG_LOCALVERSION="-XiGuan"' kernel_platform/common/arch/arm64/configs/gki_defconfig
        ls
        rm -rf common
        git clone --depth=1 https://github.com/ztc1997/android_gki_kernel_5.10_common
        mv android_gki_kernel_5.10_common common
    - name: 添加KernelSU Next
      run: |
        cd kernel/common
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        
    - name: 添加SUSFS
      run: |
           cd kernel
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10
           git clone https://github.com/TheWildJames/kernel_patches.git
           #cd kernel_platform
           cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./common/KernelSU-Next/
           cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ./common/
           cp ./susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ./susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           cd ./common/KernelSU-Next
           patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
           cd ..
           patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch || true
           cp ../kernel_patches/69_hide_stuff.patch ./
           patch -p1 -F 3 < 69_hide_stuff.patch
           cp ../kernel_patches/apk_sign.c_fix.patch ./
           patch -p1 -F 3 < apk_sign.c_fix.patch
           cp ../kernel_patches/core_hook.c_fix.patch ./
           patch -p1 --fuzz=3 < ./core_hook.c_fix.patch
           cp ../kernel_patches/selinux.c_fix.patch ./
           patch -p1 -F 3 < selinux.c_fix.patch
           cp ../kernel_patches/Makefile_fix.patch ./
           patch -p1 -F 3 < Makefile_fix.patch
           
           
    - name: 编译内核
      run: |
        cd kernel
        cd common
        sed -i '779s/^/#/' Makefile
        sed -i '1006s/^/#/' Makefile
        cd ..
        export LTO=thin
        #./kernel_platform/oplus/build/oplus_build_kernel.sh waipio gki
        echo "function check_defconfig() { return 0; }">>build/_setup_env.sh
        echo "export -f check_defconfig">>build/_setup_env.sh
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

    - name: 打包 AnyKernel3
      run: |
       git clone https://github.com/Yxiguan/AnyKernel3.git --depth=1
       rm -rf ./AnyKernel3/.git
       sudo chmod 777 ./AnyKernel3/ksu.sh
       cd ./AnyKernel3/
       ./ksu.sh
       cd ..
       cp kernel/out/android12-5.10/dist/Image ./AnyKernel3/
       
    - name: 上传 AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3_KernelSU_Next-For-xiaomi-kernel-5.10
        path: ./AnyKernel3/*

    - name: 上传 Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-KernelSU_Next-SUSFS-11R
        path: kernel/out/android12-5.10/dist/Image
